### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [indoor25/course-work_1#1]
1)
Отступы не соответствуют поставленной задаче.
![image](https://github.com/indoor25/course-work_1/assets/8464662/074b3494-486e-4d7f-8cf6-56ce28fd7d15)

![image](https://github.com/indoor25/course-work_1/assets/8464662/10683098-d2aa-4a01-a3b6-136a0c485756)

**Comment by indoor25** [comment]
Поправил
